'use client';

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { 
  Search, 
  Filter,
  Eye,
  CheckCircle,
  XCircle,
  Clock,
  Download,
  FileText,
  User,
  GraduationCap,
  ChevronLeft,
  ChevronRight
} from 'lucide-react';
import { toast } from 'sonner';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { ConfirmModal } from '@/components/ui/confirm-modal';
import { RejectModal } from '@/components/ui/reject-modal';
import { ViewApplicationModal } from '@/components/ui/view-application-modal';
import { useLanguage } from '@/contexts/LanguageContext';
import adminService, { AdminApplication } from '@/services/admin.service';

export default function ApplicationsManagement() {
  const router = useRouter();
  const { t } = useLanguage();
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedStatus, setSelectedStatus] = useState('all');
  const [currentPage, setCurrentPage] = useState(1);
  const [isLoading, setIsLoading] = useState(true);
  const [applications, setApplications] = useState<AdminApplication[]>([]);
  const [pagination, setPagination] = useState({ totalItems: 0, totalPages: 0 });
  const [viewModal, setViewModal] = useState<{ isOpen: boolean; application: AdminApplication | null }>({
    isOpen: false,
    application: null
  });
  const [approveModal, setApproveModal] = useState<{ isOpen: boolean; appId: number; studentName: string; scholarship: string }>({
    isOpen: false,
    appId: 0,
    studentName: '',
    scholarship: ''
  });
  const [rejectModal, setRejectModal] = useState<{ isOpen: boolean; appId: number; studentName: string; scholarship: string }>({
    isOpen: false,
    appId: 0,
    studentName: '',
    scholarship: ''
  });
  const [approveAllModal, setApproveAllModal] = useState(false);
  const itemsPerPage = 10;

  // Fetch applications from API
  useEffect(() => {
    const fetchApplications = async () => {
      try {
        setIsLoading(true);
        const status = selectedStatus === 'all' ? undefined : 
          selectedStatus === t('adminApplications.statusPending') ? 'PENDING' :
          selectedStatus === t('adminApplications.statusUnderReview') ? 'UNDER_REVIEW' :
          selectedStatus === t('adminApplications.statusApproved') ? 'ACCEPTED' :
          selectedStatus === t('adminApplications.statusRejected') ? 'REJECTED' : undefined;
        
        const response = await adminService.getApplications({
          page: currentPage - 1,
          size: itemsPerPage,
          status,
          keyword: searchQuery || undefined
        });
        
        setApplications(response.content);
        setPagination({
          totalItems: response.totalElements,
          totalPages: response.totalPages
        });
      } catch (error: any) {
        console.error('Failed to fetch applications:', error);
        toast.error('Không thể tải danh sách đơn ứng tuyển', {
          description: error.message || 'Vui lòng thử lại sau'
        });
      } finally {
        setIsLoading(false);
      }
    };

    fetchApplications();
  }, [currentPage, selectedStatus, searchQuery, t]);

  // Handlers
  const handleExportReport = () => {
    const date = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });

    const reportContent = `
EduMatch Applications Report
Generated: ${date}

===========================================
APPLICATIONS SUMMARY
===========================================

Total Applications: ${applications.length}
- Pending: ${stats.pending}
- Under Review: ${stats.underReview}
- Approved: ${stats.approved}
- Rejected: ${stats.rejected}

===========================================
DETAILED APPLICATIONS
===========================================

${applications.map((app, i) => `
${i + 1}. ${app.id}
   Student: ${app.studentName} (${app.studentEmail})
   Scholarship: ${app.scholarship}
   Provider: ${app.provider}
   Amount: ${app.amount}
   GPA: ${app.gpa}
   Status: ${app.status}
   Submitted: ${app.submittedDate}
   Documents: ${app.documents}
`).join('\n')}

===========================================
Generated by EduMatch Admin System
===========================================
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `applications-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);

    toast.success(t('adminApplications.reportExported'), {
      description: t('adminApplications.reportExportedDesc'),
    });
  };

  const handleViewApplication = async (appId: number) => {
    try {
      const app = await adminService.getApplicationById(appId);
      setViewModal({ isOpen: true, application: app });
    } catch (error: any) {
      toast.error('Không thể tải chi tiết đơn ứng tuyển', {
        description: error.message || 'Vui lòng thử lại sau'
      });
    }
  };

  const handleApproveApplication = (appId: number, studentName: string, scholarship: string) => {
    setApproveModal({ isOpen: true, appId, studentName, scholarship });
  };

  const confirmApproveApplication = async () => {
    try {
      await adminService.updateApplicationStatus(approveModal.appId, 'ACCEPTED');
      toast.success(t('adminApplications.applicationApproved'), {
        description: t('adminApplications.applicationApprovedDesc').replace('{name}', approveModal.studentName),
      });
      setApproveModal({ isOpen: false, appId: 0, studentName: '', scholarship: '' });
      // Refresh list
      const status = selectedStatus === 'all' ? undefined : 
        selectedStatus === t('adminApplications.statusPending') ? 'PENDING' :
        selectedStatus === t('adminApplications.statusUnderReview') ? 'UNDER_REVIEW' :
        selectedStatus === t('adminApplications.statusApproved') ? 'ACCEPTED' :
        selectedStatus === t('adminApplications.statusRejected') ? 'REJECTED' : undefined;
      
      const response = await adminService.getApplications({
        page: currentPage - 1,
        size: itemsPerPage,
        status,
        keyword: searchQuery || undefined
      });
      setApplications(response.content);
    } catch (error: any) {
      toast.error('Không thể duyệt đơn ứng tuyển', {
        description: error.message || 'Vui lòng thử lại sau'
      });
    }
  };

  const handleRejectApplication = (appId: number, studentName: string, scholarship: string) => {
    setRejectModal({ isOpen: true, appId, studentName, scholarship });
  };

  const confirmRejectApplication = async (reason: string) => {
    try {
      await adminService.updateApplicationStatus(rejectModal.appId, 'REJECTED');
      toast.error(t('adminApplications.applicationRejected'), {
        description: t('adminApplications.applicationRejectedDesc').replace('{name}', rejectModal.studentName),
      });
      setRejectModal({ isOpen: false, appId: 0, studentName: '', scholarship: '' });
      // Refresh list
      const status = selectedStatus === 'all' ? undefined : 
        selectedStatus === t('adminApplications.statusPending') ? 'PENDING' :
        selectedStatus === t('adminApplications.statusUnderReview') ? 'UNDER_REVIEW' :
        selectedStatus === t('adminApplications.statusApproved') ? 'ACCEPTED' :
        selectedStatus === t('adminApplications.statusRejected') ? 'REJECTED' : undefined;
      
      const response = await adminService.getApplications({
        page: currentPage - 1,
        size: itemsPerPage,
        status,
        keyword: searchQuery || undefined
      });
      setApplications(response.content);
    } catch (error: any) {
      toast.error('Không thể từ chối đơn ứng tuyển', {
        description: error.message || 'Vui lòng thử lại sau'
      });
    }
  };

  const handleApproveAll = () => {
    setApproveAllModal(true);
  };

  const confirmApproveAll = async () => {
    try {
      const pendingApps = applications.filter(app => app.status === 'PENDING');
      // TODO: Implement approve all API when available
      toast.success(t('adminApplications.allApproved'), {
        description: t('adminApplications.allApprovedDesc').replace('{count}', pendingApps.length.toString()),
      });
      setApproveAllModal(false);
      // Refresh list
      setCurrentPage(1);
    } catch (error: any) {
      toast.error('Không thể duyệt tất cả đơn ứng tuyển', {
        description: error.message || 'Vui lòng thử lại sau'
      });
    }
  };

  const getStatusColor = (status: string) => {
    if (status === 'ACCEPTED') return 'bg-green-100 text-green-700';
    if (status === 'PENDING' || status === 'SUBMITTED') return 'bg-yellow-100 text-yellow-700';
    if (status === 'VIEWED' || status === 'UNDER_REVIEW') return 'bg-blue-100 text-blue-700';
    if (status === 'REJECTED') return 'bg-red-100 text-red-700';
    return 'bg-gray-100 text-gray-700';
  };

  const getStatusIcon = (status: string) => {
    if (status === 'ACCEPTED') return <CheckCircle className="w-4 h-4" />;
    if (status === 'PENDING' || status === 'SUBMITTED') return <Clock className="w-4 h-4" />;
    if (status === 'VIEWED' || status === 'UNDER_REVIEW') return <Eye className="w-4 h-4" />;
    if (status === 'REJECTED') return <XCircle className="w-4 h-4" />;
    return null;
  };

  const stats = {
    total: pagination.totalItems,
    pending: applications.filter(a => a.status === 'PENDING' || a.status === 'SUBMITTED').length,
    underReview: applications.filter(a => a.status === 'VIEWED' || a.status === 'UNDER_REVIEW').length,
    approved: applications.filter(a => a.status === 'ACCEPTED').length,
    rejected: applications.filter(a => a.status === 'REJECTED').length
  };

  const getStatusLabel = (status: string) => {
    if (status === 'ACCEPTED') return t('adminApplications.statusApproved');
    if (status === 'REJECTED') return t('adminApplications.statusRejected');
    if (status === 'VIEWED' || status === 'UNDER_REVIEW') return t('adminApplications.statusUnderReview');
    if (status === 'PENDING' || status === 'SUBMITTED') return t('adminApplications.statusPending');
    return status;
  };

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">{t('adminApplications.title')}</h1>
          <p className="text-gray-500 mt-1">{t('adminApplications.subtitle')}</p>
        </div>
        <div className="flex gap-3">
          <Button 
            onClick={handleApproveAll}
            disabled={stats.pending === 0}
            className="bg-green-600 hover:bg-green-700 disabled:bg-gray-300"
          >
            <CheckCircle className="w-4 h-4 mr-2" />
            {t('adminApplications.approveAll')} ({stats.pending})
          </Button>
          <Button 
            onClick={handleExportReport}
            variant="outline"
          >
            <Download className="w-4 h-4 mr-2" />
            {t('adminApplications.exportReport')}
          </Button>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
        <Card className="card-minimal">
          <CardContent className="p-4">
            <p className="text-sm text-gray-500">{t('adminApplications.total')}</p>
            <h3 className="text-2xl font-bold text-gray-900 mt-1">{stats.total}</h3>
          </CardContent>
        </Card>
        <Card className="card-minimal">
          <CardContent className="p-4">
            <p className="text-sm text-gray-500">{t('adminApplications.pending')}</p>
            <h3 className="text-2xl font-bold text-yellow-600 mt-1">{stats.pending}</h3>
          </CardContent>
        </Card>
        <Card className="card-minimal">
          <CardContent className="p-4">
            <p className="text-sm text-gray-500">{t('adminApplications.underReview')}</p>
            <h3 className="text-2xl font-bold text-blue-600 mt-1">{stats.underReview}</h3>
          </CardContent>
        </Card>
        <Card className="card-minimal">
          <CardContent className="p-4">
            <p className="text-sm text-gray-500">{t('adminApplications.approved')}</p>
            <h3 className="text-2xl font-bold text-green-600 mt-1">{stats.approved}</h3>
          </CardContent>
        </Card>
        <Card className="card-minimal">
          <CardContent className="p-4">
            <p className="text-sm text-gray-500">{t('adminApplications.rejected')}</p>
            <h3 className="text-2xl font-bold text-red-600 mt-1">{stats.rejected}</h3>
          </CardContent>
        </Card>
      </div>

      {/* Filters and Search */}
      <Card className="card-minimal">
        <CardContent className="p-6">
          <div className="flex flex-col lg:flex-row gap-4">
            {/* Search */}
            <div className="flex-1 relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
              <input
                type="text"
                placeholder={t('adminApplications.searchPlaceholder')}
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>

            {/* Status Filter */}
            <select
              value={selectedStatus}
              onChange={(e) => setSelectedStatus(e.target.value)}
              className="px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="all">{t('adminApplications.allStatus')}</option>
              <option value={t('adminApplications.statusPending')}>{t('adminApplications.statusPending')}</option>
              <option value={t('adminApplications.statusUnderReview')}>{t('adminApplications.statusUnderReview')}</option>
              <option value={t('adminApplications.statusApproved')}>{t('adminApplications.statusApproved')}</option>
              <option value={t('adminApplications.statusRejected')}>{t('adminApplications.statusRejected')}</option>
            </select>
          </div>
        </CardContent>
      </Card>

      {/* Applications Table */}
      <Card className="card-minimal">
        <CardContent className="p-0">
          {isLoading ? (
            <div className="p-6 text-center">
              <p className="text-gray-500">Đang tải...</p>
            </div>
          ) : applications.length === 0 ? (
            <div className="p-6 text-center">
              <p className="text-gray-500">Không có đơn ứng tuyển nào</p>
            </div>
          ) : (
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50 border-b border-gray-200">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    {t('adminApplications.applicationId')}
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    {t('adminApplications.student')}
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    {t('adminApplications.scholarship')}
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    {t('adminApplications.gpa')}
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    {t('adminApplications.status')}
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    {t('adminApplications.submitted')}
                  </th>
                  <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                    {t('adminApplications.actions')}
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {applications.map((app) => (
                  <tr key={app.id} className="hover:bg-gray-50 transition-colors">
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center">
                        <FileText className="w-4 h-4 text-gray-400 mr-2" />
                        <span className="font-mono text-sm font-semibold text-gray-900">
                          #{app.id}
                        </span>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center">
                        <div className="w-8 h-8 rounded-full bg-blue-600 flex items-center justify-center text-white text-xs font-semibold">
                          {(app.applicantUserName || 'U').split(' ').map(n => n[0]).join('').substring(0, 2)}
                        </div>
                        <div className="ml-3">
                          <div className="font-semibold text-gray-900">{app.applicantUserName || 'Unknown'}</div>
                          <div className="text-xs text-gray-500">{app.applicantEmail || ''}</div>
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <div>
                        <div className="font-semibold text-gray-900">{app.opportunityTitle || `Opportunity #${app.opportunityId}`}</div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="font-semibold text-gray-900">{app.gpa?.toFixed(2) || 'N/A'}</span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <Badge className={`${getStatusColor(app.status)} flex items-center gap-1 w-fit`}>
                        {getStatusIcon(app.status)}
                        {getStatusLabel(app.status)}
                      </Badge>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {app.submittedAt ? new Date(app.submittedAt).toLocaleDateString() : 
                       app.createdAt ? new Date(app.createdAt).toLocaleDateString() : 'N/A'}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-right">
                      <div className="flex items-center justify-end gap-2">
                        <Button 
                          variant="outline" 
                          size="sm"
                          onClick={() => handleViewApplication(app.id)}
                          title={t('adminApplications.viewDetails')}
                        >
                          <Eye className="w-4 h-4" />
                        </Button>
                        {(app.status === 'PENDING' || app.status === 'SUBMITTED' || app.status === 'VIEWED' || app.status === 'UNDER_REVIEW') ? (
                          <>
                            <Button 
                              variant="outline" 
                              size="sm" 
                              className="text-green-600 hover:text-green-700"
                              onClick={() => handleApproveApplication(app.id, app.applicantUserName || 'Unknown', app.opportunityTitle || `Opportunity #${app.opportunityId}`)}
                              title="Accept"
                            >
                              <CheckCircle className="w-4 h-4" />
                            </Button>
                            <Button 
                              variant="outline" 
                              size="sm" 
                              className="text-red-600 hover:text-red-700"
                              onClick={() => handleRejectApplication(app.id, app.applicantUserName || 'Unknown', app.opportunityTitle || `Opportunity #${app.opportunityId}`)}
                              title="Reject"
                            >
                              <XCircle className="w-4 h-4" />
                            </Button>
                            {(app.status === 'PENDING' || app.status === 'SUBMITTED') && (
                              <Button 
                                variant="outline" 
                                size="sm" 
                                className="text-blue-600 hover:text-blue-700"
                                onClick={async () => {
                                  try {
                                    await adminService.updateApplicationStatus(app.id, 'UNDER_REVIEW');
                                    toast.info('Đã đánh dấu là đang xem xét');
                                    // Refresh list
                                    const status = selectedStatus === 'all' ? undefined : 
                                      selectedStatus === t('adminApplications.statusPending') ? 'PENDING' :
                                      selectedStatus === t('adminApplications.statusUnderReview') ? 'UNDER_REVIEW' :
                                      selectedStatus === t('adminApplications.statusApproved') ? 'ACCEPTED' :
                                      selectedStatus === t('adminApplications.statusRejected') ? 'REJECTED' : undefined;
                                    
                                    const response = await adminService.getApplications({
                                      page: currentPage - 1,
                                      size: itemsPerPage,
                                      status,
                                      keyword: searchQuery || undefined
                                    });
                                    setApplications(response.content);
                                  } catch (error: any) {
                                    toast.error('Không thể cập nhật trạng thái', {
                                      description: error.message || 'Vui lòng thử lại sau'
                                    });
                                  }
                                }}
                                title="Mark Under Review"
                              >
                                <Clock className="w-4 h-4" />
                              </Button>
                            )}
                          </>
                        ) : null}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          )}

          {/* Pagination */}
          <div className="px-6 py-4 border-t border-gray-200 flex items-center justify-between">
            <p className="text-sm text-gray-500">
              {t('adminApplications.showingResults')
                .replace('{start}', ((currentPage - 1) * itemsPerPage + 1).toString())
                .replace('{end}', Math.min(currentPage * itemsPerPage, pagination.totalItems).toString())
                .replace('{total}', pagination.totalItems.toString())}
            </p>
            <div className="flex items-center gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={() => setCurrentPage(prev => Math.max(1, prev - 1))}
                disabled={currentPage === 1 || isLoading}
              >
                <ChevronLeft className="w-4 h-4" />
                {t('adminApplications.previous')}
              </Button>
              <span className="text-sm text-gray-700">
                Page {currentPage} of {pagination.totalPages || 1}
              </span>
              <Button
                variant="outline"
                size="sm"
                onClick={() => setCurrentPage(prev => Math.min(pagination.totalPages || 1, prev + 1))}
                disabled={currentPage >= (pagination.totalPages || 1) || isLoading}
              >
                {t('adminApplications.next')}
                <ChevronRight className="w-4 h-4" />
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Approve Confirmation Modal */}
      <ConfirmModal
        isOpen={approveModal.isOpen}
        onClose={() => setApproveModal({ isOpen: false, appId: 0, studentName: '', scholarship: '' })}
        onConfirm={confirmApproveApplication}
        title={t('adminApplications.confirmApprove')}
        description={t('adminApplications.confirmApproveDesc').replace('{name}', approveModal.studentName).replace('{scholarship}', approveModal.scholarship)}
        variant="success"
        confirmText={t('adminApplications.confirmApproveBtn')}
      />

      {/* Approve All Confirmation Modal */}
      <ConfirmModal
        isOpen={approveAllModal}
        onClose={() => setApproveAllModal(false)}
        onConfirm={confirmApproveAll}
        title={t('adminApplications.confirmApproveAll')}
        description={t('adminApplications.confirmApproveAllDesc').replace('{count}', stats.pending.toString())}
        variant="success"
        confirmText={t('adminApplications.confirmApproveAllBtn')}
      />

      {/* Reject Modal */}
      <RejectModal
        isOpen={rejectModal.isOpen}
        onClose={() => setRejectModal({ isOpen: false, appId: 0, studentName: '', scholarship: '' })}
        onSubmit={confirmRejectApplication}
        title={t('adminApplications.confirmReject').replace('{name}', rejectModal.studentName)}
        placeholder={t('adminApplications.rejectPlaceholder')}
      />

      {/* View Application Detail Modal */}
      <ViewApplicationModal
        isOpen={viewModal.isOpen}
        onClose={() => setViewModal({ isOpen: false, application: null })}
        application={viewModal.application}
      />
    </div>
  );
}
