'use client';

import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { 
  Users, 
  GraduationCap, 
  FileText, 
  TrendingUp,
  ArrowUpRight,
  ArrowDownRight,
  Calendar,
  DollarSign
} from 'lucide-react';
import { toast } from 'sonner';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { adminService, AdminStats } from '@/services/admin.service';
import { formatDistanceToNow } from 'date-fns';
import { useLanguage } from '@/contexts/LanguageContext';
import Link from 'next/link';
import { pageVariants, statCardVariants, listContainerVariants, listItemVariants } from '@/lib/animations';

export default function AdminDashboard() {
  const { t } = useLanguage();
  const [stats, setStats] = useState<AdminStats | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchStats = async () => {
      try {
        setIsLoading(true);
        const data = await adminService.getStats();
        setStats(data);
      } catch (error: any) {
        console.error('Failed to fetch admin stats:', error);
        toast.error('Không thể tải thống kê', {
          description: error.message || 'Vui lòng thử lại sau'
        });
      } finally {
        setIsLoading(false);
      }
    };

    fetchStats();
  }, []);

  // Calculate stats from API data
  const totalUsers = stats?.totalUsers || 0;
  const activeScholarships = stats?.activeScholarships || 0;
  const pendingApplications = stats?.pendingApplications || 0;
  const totalFunding = 0; // TODO: Calculate from scholarships if needed

  const handleGenerateReport = () => {
    // Get current date for report
    const date = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });

    // Create report data
    const reportData = {
      date,
      totalUsers: stats?.totalUsers || 0,
      activeScholarships: stats?.activeScholarships || 0,
      pendingApplications: stats?.pendingApplications || 0,
      totalFunding,
      students: stats?.totalStudents || 0,
      providers: stats?.totalEmployers || 0,
      acceptedApplications: stats?.acceptedApplications || 0,
      rejectedApplications: stats?.rejectedApplications || 0,
      totalApplications: stats?.totalApplications || 0,
    };

    // Create report content
    const reportContent = `
EduMatch Admin Report
Generated: ${reportData.date}

===========================================
SYSTEM OVERVIEW
===========================================

Users Statistics:
- Total Users: ${reportData.totalUsers}
- Students: ${reportData.students}
- Providers: ${reportData.providers}

Scholarships Statistics:
- Active Scholarships: ${reportData.activeScholarships}
- Total Funding Available: $${reportData.totalFunding.toLocaleString()}

Applications Statistics:
- Pending Applications: ${reportData.pendingApplications}
- Accepted Applications: ${reportData.acceptedApplications}
- Rejected Applications: ${reportData.rejectedApplications}
- Total Applications: ${reportData.totalApplications}

===========================================
DETAILED BREAKDOWN
===========================================

Recent Applications:
(Data will be loaded from API)

Recent Users:
(Data will be loaded from API)

===========================================
Generated by EduMatch Admin System
===========================================
    `.trim();

    // Create and download report
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `edumatch-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);

    // Show success message
    toast.success(t('admin.report.success'), {
      description: t('admin.report.successDescription'),
    });
  };

  const statsCards = [
    {
      title: t('admin.stats.totalUsers'),
      value: isLoading ? '...' : totalUsers.toLocaleString(),
      change: '+12.5%',
      trend: 'up' as const,
      icon: Users,
      color: 'bg-blue-500',
      link: '/admin/users'
    },
    {
      title: t('admin.stats.activeScholarships'),
      value: isLoading ? '...' : activeScholarships.toLocaleString(),
      change: '+5.2%',
      trend: 'up' as const,
      icon: GraduationCap,
      color: 'bg-green-500',
      link: '/admin/scholarships'
    },
    {
      title: t('admin.stats.pendingApplications'),
      value: isLoading ? '...' : pendingApplications.toLocaleString(),
      change: '-3.1%',
      trend: 'down' as const,
      icon: FileText,
      color: 'bg-orange-500',
      link: '/admin/applications'
    },
    {
      title: t('admin.stats.totalFunding'),
      value: isLoading ? '...' : `$${(totalFunding / 1000).toFixed(1)}K`,
      change: '+18.2%',
      trend: 'up' as const,
      icon: DollarSign,
      color: 'bg-purple-500',
      link: '/admin/scholarships'
    }
  ];

  // Placeholder for recent applications - can be loaded from API later
  const recentApplications: any[] = [];

  // Placeholder for recent users - can be loaded from API later
  const recentUsers: any[] = [];

  const getStatusColor = (status: string) => {
    if (status.includes('accepted')) return 'bg-green-100 text-green-700';
    if (status.includes('submitted') || status.includes('under review')) return 'bg-yellow-100 text-yellow-700';
    if (status.includes('rejected')) return 'bg-red-100 text-red-700';
    return 'bg-gray-100 text-gray-700';
  };

  return (
    <motion.div
      className="space-y-6"
      variants={pageVariants}
      initial="initial"
      animate="animate"
      exit="exit"
    >
      {/* Page Header */}
      <motion.div
        className="flex items-center justify-between"
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
      >
        <div>
          <h1 className="text-3xl font-bold text-gray-900">{t('admin.dashboard.title')}</h1>
          <p className="text-gray-500 mt-1">{t('admin.dashboard.subtitle')}</p>
        </div>
        <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
          <Button 
            onClick={handleGenerateReport}
            className="bg-blue-600 hover:bg-blue-700"
          >
            <Calendar className="w-4 h-4 mr-2" />
            {t('admin.dashboard.generateReport')}
          </Button>
        </motion.div>
      </motion.div>

      {/* Stats Grid */}
      <motion.div
        className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6"
        variants={listContainerVariants}
        initial="initial"
        animate="animate"
      >
        {statsCards.map((stat, index) => {
          const Icon = stat.icon;
          const TrendIcon = stat.trend === 'up' ? ArrowUpRight : ArrowDownRight;
          
          return (
            <motion.div key={index} variants={listItemVariants}>
              <motion.div variants={statCardVariants} whileHover="hover">
                <Card className="card-minimal">
                  <CardContent className="p-6">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex-1">
                    <p className="text-sm font-medium text-gray-500">{stat.title}</p>
                    <h3 className="text-3xl font-bold text-gray-900 mt-2">{stat.value}</h3>
                    <div className="flex items-center mt-2">
                      <TrendIcon 
                        className={`w-4 h-4 ${
                          stat.trend === 'up' ? 'text-green-600' : 'text-red-600'
                        }`} 
                      />
                      <span 
                        className={`text-sm font-medium ml-1 ${
                          stat.trend === 'up' ? 'text-green-600' : 'text-red-600'
                        }`}
                      >
                        {stat.change}
                      </span>
                      <span className="text-sm text-gray-500 ml-1">{t('admin.stats.vsLastMonth')}</span>
                    </div>
                  </div>
                  <div className={`${stat.color} w-12 h-12 rounded-lg flex items-center justify-center`}>
                    <Icon className="w-6 h-6 text-white" />
                  </div>
                </div>
                <Link href={stat.link}>
                  <Button variant="outline" size="sm" className="w-full">
                    {t('admin.stats.viewAll')}
                  </Button>
                </Link>
              </CardContent>
            </Card>
              </motion.div>
            </motion.div>
          );
        })}
      </motion.div>

      <motion.div
        className="grid grid-cols-1 lg:grid-cols-2 gap-6"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.4, duration: 0.5 }}
      >
        {/* Recent Applications */}
        <Card className="card-minimal">
          <CardHeader>
            <CardTitle className="text-lg font-semibold">{t('admin.recentApplications.title')}</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {recentApplications.length > 0 ? recentApplications.map((application) => (
                <div 
                  key={application.id}
                  className="flex items-center justify-between p-4 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors"
                >
                  <div className="flex-1">
                    <h4 className="font-semibold text-gray-900">{application.studentName}</h4>
                    <p className="text-sm text-gray-600">{application.scholarship}</p>
                    <p className="text-xs text-gray-500 mt-1">{application.date}</p>
                  </div>
                  <div className="text-right">
                    <p className="font-semibold text-gray-900">{application.amount}</p>
                    <Badge className={`mt-1 ${getStatusColor(application.status)}`}>
                      {application.status}
                    </Badge>
                  </div>
                </div>
              )) : (
                <div className="text-center py-8 text-gray-500">
                  <FileText className="w-12 h-12 mx-auto mb-2 text-gray-400" />
                  <p>Chưa có đơn ứng tuyển gần đây</p>
                </div>
              )}
            </div>
            <Button variant="outline" className="w-full mt-4">
              {t('admin.recentApplications.viewAll')}
            </Button>
          </CardContent>
        </Card>

        {/* Recent Users */}
        <Card className="card-minimal">
          <CardHeader>
            <CardTitle className="text-lg font-semibold">{t('admin.recentUsers.title')}</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {recentUsers.length > 0 ? recentUsers.map((user) => (
                <div 
                  key={user.id}
                  className="flex items-center gap-4 p-4 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors"
                >
                  <div className="w-12 h-12 rounded-full bg-blue-600 flex items-center justify-center text-white font-semibold">
                    {user.avatar}
                  </div>
                  <div className="flex-1">
                    <h4 className="font-semibold text-gray-900">{user.name}</h4>
                    <p className="text-sm text-gray-600">{user.email}</p>
                    <p className="text-xs text-gray-500 mt-1">{user.joinDate}</p>
                  </div>
                  <Badge variant="secondary">{user.role}</Badge>
                </div>
              )) : (
                <div className="text-center py-8 text-gray-500">
                  <Users className="w-12 h-12 mx-auto mb-2 text-gray-400" />
                  <p>Chưa có người dùng gần đây</p>
                </div>
              )}
            </div>
            <Button variant="outline" className="w-full mt-4">
              {t('admin.recentUsers.viewAll')}
            </Button>
          </CardContent>
        </Card>
      </motion.div>

      {/* Activity Chart Placeholder */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.6, duration: 0.5 }}
      >
        <Card className="card-minimal">
        <CardHeader>
          <CardTitle className="text-lg font-semibold">{t('admin.activity.title')}</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="h-64 flex items-center justify-center bg-gray-50 rounded-lg">
            <div className="text-center">
              <TrendingUp className="w-12 h-12 text-gray-400 mx-auto mb-2" />
              <p className="text-gray-500">{t('admin.activity.chartComingSoon')}</p>
              <p className="text-sm text-gray-400 mt-1">{t('admin.activity.chartPending')}</p>
            </div>
          </div>
        </CardContent>
      </Card>
      </motion.div>
    </motion.div>
  );
}
